Repository inhindsight/hindsight, pull requests merged in 2020-05, with the labels that each got.

#242 Ability to extend hindsight with custom protocol implementations
  Dockerfile
  apps/plugins/.formatter.exs
  apps/plugins/.gitignore
  apps/plugins/README.md
  apps/plugins/lib/plugins.ex
  apps/plugins/mix.exs
  apps/plugins/test/plugins/bad/broken_plugin.ex
  apps/plugins/test/plugins/bad/unloaded_plugin.ex
  apps/plugins/test/plugins/empty/.gitkeep
  apps/plugins/test/plugins/good/plugin_file_one.ex
  apps/plugins/test/plugins/good/plugin_file_two.ex
  apps/plugins/test/plugins_test.exs
  apps/plugins/test/test_helper.exs
  apps/service_acquire/lib/acquire/application.ex
  apps/service_acquire/mix.exs
  apps/service_broadcast/lib/broadcast/application.ex
  apps/service_broadcast/mix.exs
  apps/service_gather/lib/gather/application.ex
  apps/service_gather/mix.exs
  apps/service_orchestrate/lib/orchestrate/application.ex
  apps/service_orchestrate/mix.exs
  apps/service_persist/lib/persist/application.ex
  apps/service_persist/mix.exs
  apps/service_profile/lib/profile/application.ex
  apps/service_profile/mix.exs
  apps/service_receive/lib/receive/application.ex
  apps/service_receive/mix.exs
Labels: enhancement

#246 Backpressure worldwide
  apps/extractor/lib/extractor/server.ex
  apps/protocol_source/lib/source/handler.ex
  apps/service_gather/config/test.exs
  apps/service_gather/lib/gather/extraction.ex
  apps/service_gather/lib/gather/extraction/source_handler.ex
  apps/service_gather/lib/gather/extraction/source_stream.ex
  apps/service_gather/test/gather/extraction_test.exs
  apps/testing/lib/source/fake.ex
  config/releases.exs
Labels: performance

#252 Dictionary.Type.Timestamp default format value
  apps/definition_dictionary/lib/dictionary/type/timestamp.ex
  apps/definition_dictionary/test/dictionary/type/timestamp_test.exs
Labels: event
